spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: syy1994
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8


