spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.62.148:3306/person?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: person
    password: 123456
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
server:
  port: 8089
  tomcat:
    uri-encoding: utf-8


